In [1]:
import pandas as pd

In [2]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from seaborn) (2.2.6)
Requirement already satisfied: pandas>=1.2 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\user\documents\myproject\datamining\data_mining_project2\data_mining_student_performance\env\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

## Import Libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder
from sklearn.impute import KNNImputer
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.ensemble import RandomForestRegressor

In [5]:
import os
print(os.getcwd())  
print(os.listdir())

C:\Users\User\Documents\MyProject\DataMining\Data_mining_project2\Data_mining_student_performance\notebooks
['.ipynb_checkpoints', 'data_preprocessing.ipynb', 'student.csv']

In [6]:
import os
print(os.getcwd())

C:\Users\User\Documents\MyProject\DataMining\Data_mining_project2\Data_mining_student_performance\notebooks

## Load Dataset

In [7]:
df = pd.read_csv("student.csv", sep=';')
print(df.head())

  # Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:
0  1 school - student's school (binary: "GP" - Ga...
1  2 sex - student's sex (binary: "F" - female or...
2     3 age - student's age (numeric: from 15 to 22)
3  4 address - student's home address type (binar...
4  5 famsize - family size (binary: "LE3" - less ...

In [17]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df = pd.read_csv("student.csv", sep=';')
print(df)

   # Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:
0   1 school - student's school (binary: "GP" - Ga...
1   2 sex - student's sex (binary: "F" - female or...
2      3 age - student's age (numeric: from 15 to 22)
3   4 address - student's home address type (binar...
4   5 famsize - family size (binary: "LE3" - less ...
5   6 Pstatus - parent's cohabitation status (bina...
6   7 Medu - mother's education (numeric: 0 - none...
7   8 Fedu - father's education (numeric: 0 - none...
8   9 Mjob - mother's job (nominal: "teacher", "he...
9   10 Fjob - father's job (nominal: "teacher", "h...
10  11 reason - reason to choose this school (nomi...
11  12 guardian - student's guardian (nominal: "mo...
12  13 traveltime - home to school travel time (nu...
13  14 studytime - weekly study time (numeric: 1 -...
14  15 failures - number of past class failures (n...
15  16 schoolsup - extra educational support (bina...
16  17 famsup - family educational support (binary...
17  18 paid - extra paid classes within the course...
18  19 activities - extra-curricular activities (b...
19  20 nursery - attended nursery school (binary: ...
20  21 higher - wants to take higher education (bi...
21  22 internet - Internet access at home (binary:...
22  23 romantic - with a romantic relationship (bi...
23  24 famrel - quality of family relationships (n...
24  25 freetime - free time after school (numeric:...
25  26 goout - going out with friends (numeric: fr...
26  27 Dalc - workday alcohol consumption (numeric...
27  28 Walc - weekend alcohol consumption (numeric...
28  29 health - current health status (numeric: fr...
29  30 absences - number of school absences (numer...
30  # these grades are related with the course sub...
31  31 G1 - first period grade (numeric: from 0 to...
32  31 G2 - second period grade (numeric: from 0 t...
33  32 G3 - final grade (numeric: from 0 to 20, ou...
34  Additional note: there are several (382) stude...
35  These students can be identified by searching ...
36  that characterize each student, as shown in th...

In [18]:
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 1 columns):
 #   Column                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                          --------------  -----
 0   # Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:  37 non-null     object
dtypes: object(1)
memory usage: 424.0+ bytes

       # Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:
count                                                  37
unique                                                 37
top     1 school - student's school (binary: "GP" - Ga...
freq                                                    1

### ***DATA CLEANING

##### Check Missing Values

In [19]:
df.isnull().sum()

# Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:    0
dtype: int64

In [21]:
df = pd.read_csv("student.csv" , sep=';')

In [22]:
df = df[df.columns[0]].str.split(';', expand=True)

In [23]:
df = df[df.columns[0]].str.split(',', expand=True)

In [24]:
df.columns = df.iloc[0]
df = df[1:]

In [25]:
df.head()

,"1 school - student's school (binary: ""GP"" - Gabriel Pereira or ""MS"" - Mousinho da Silveira)",None,None,None
1,"2 sex - student's sex (binary: ""F"" - female or...",None,None,None
2,3 age - student's age (numeric: from 15 to 22),None,None,None
3,4 address - student's home address type (binar...,None,None,None
4,"5 famsize - family size (binary: ""LE3"" - less ...",None,None,None
5,6 Pstatus - parent's cohabitation status (bina...,None,None,None

## Handle Missing Values

In [30]:
print(data.columns)

Index(['# Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:'], dtype='object')

In [32]:
data = pd.read_csv("student.csv", sep=';')
print(data.head())
print(data.columns)

  # Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:
0  1 school - student's school (binary: "GP" - Ga...
1  2 sex - student's sex (binary: "F" - female or...
2     3 age - student's age (numeric: from 15 to 22)
3  4 address - student's home address type (binar...
4  5 famsize - family size (binary: "LE3" - less ...
Index(['# Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:'], dtype='object')

#### Discard rows

In [34]:
data = data.dropna()

#### OUTLIER DETECTION

In [35]:
Q1 = data['absences'].quantile(0.25)
Q3 = data['absences'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = data[(data['absences'] < lower) | (data['absences'] > upper)]

KeyError: 'absences'